# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c55fcad97d7ddac8f9955563dbb88784866da121039b1f18228ca082da774196b56c159799d8900798dd54af693a86105addd2e912abb35802cc5f8688307692

test:
  secret_key_base: fba3496d4f7c54069eef755da0074350e4a2dece031d7c7e1b0d5d033c60b6e165aa473c92e3c5bf35281eed22c3fe29a0f7879667e04ca60b3dff357d1ecc67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
